version: "3"
services:
    firebase:
        build: .
        ports:
          - "8088:8088"
        logging:
          driver: "json-file"
          options:
            max-file: "5"
            max-size: "100m"